name: build with docker

on:
# - push
# - pull_request
- workflow_dispatch


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout This Repo
      uses: actions/checkout@v3
      
    - name: docker build image from Dockerfile
      run: |
        set -x

        docker build -t mumble-build-container-image - < $(pwd)/Dockerfile
        
    - name: Create dist directory
      run: |
        mkdir -p dist
        
    - name: Docker run static mumble build container to access binary
      run: |
        docker run --rm \
          -v $(pwd)/dist:/root/mumble/build \
          mumble-build-container-image
          
    - name: Upload a Build Artifact As-Is
      uses: actions/upload-artifact@v3
      with:
        path: dist/

