name: Build

on:
- push
- pull_request

# Package search: https://rpmfind.net/linux/rpm2html/search.php
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout This Repo
      uses: actions/checkout@v3
    - name: Checkout Mumble Repo
      uses: actions/checkout@v3
      with:
        repository: mumble-voip/mumble
        path: mumble
        submodules: recursive
    - name: list results
      run: |
        ls -l
