name: Build

on:
- push
- pull_request

# Package search: https://rpmfind.net/linux/rpm2html/search.php
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Run Docker Build Container
      run: docker build .
    - name: list results
      run: |
        ls -l
