name: Build

on:
- push
- pull_request

# Package search: https://rpmfind.net/linux/rpm2html/search.php
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout This Repo
      uses: actions/checkout@v3
    - name: Checkout Mumble Repo
      uses: actions/checkout@v3
      with:
        repository: mumble-voip/mumble
        path: mumble
        ref: v1.4.287
        submodules: recursive
    - name: Create dist directory
      run: |
        mkdir -p dist
    - name: Docker run static mumble build container
      run: |
        docker run --rm \
          -v $(pwd)/mumble:/mumble-build/sources \
          -v $(pwd)/dist:/mumble-build/dist \
          -v $(pwd)/mumble-static-build-script.sh:/mumble-build/build-mumble.sh \
          --name mumble-build-container ubuntu:20.04 \
          bash /mumble-build/build-mumble.sh
    - name: List Results
      run: |
        ls -l
    - name: List build artifacts
      run: |
        ls -l dist/
