name: build with docker

on:
# - push
# - pull_request
- workflow_dispatch

env:
  VERSION: 1.4.287

# Package search: https://rpmfind.net/linux/rpm2html/search.php
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout This Repo
      uses: actions/checkout@v3
    - name: docker build
      uses: docker-practice/actions-setup-docker@master
      run: |
        set -x

        docker build - < $(pwd)/Dockerfile

