name: Build

on:
- push
- pull_request

# Package search: https://rpmfind.net/linux/rpm2html/search.php
jobs:
  main:
    runs-on: ubuntu-latest
    container:
        image: quay.io/pypa/manylinux2014_x86_64
    steps:
    - name: Read Dockerfile
      id: Dockerfile
      uses: juliangruber/read-file-action@v1
      with:
        path: ${GITHUB_WORKSPACE}/Dockerfile
    - name: Echo Dockerfile
      run: echo "${{ steps.Dockerfile.outputs.content }}"
    - name: list results
      run: |
        ls -l
